# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 24.x]

    steps:
    - name: Update apt-get cache
      run: sudo apt-get update

    - name: Install Debian packages
      run: sudo apt-get install -y libxml2-utils xsltproc

    - name: Checkout
      uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    - run: npm ci

    - run: npm test
